export const TASK_ERROR_CONST = {
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  DOC_NOT_COMPLETELY_SIGNED: 'DOC_NOT_COMPLETELY_SIGNED',
  USER_IDENTITY_VERIFICATION_PENDING: 'USER_IDENTITY_VERIFICATION_PENDING',
};
export const TASK_ERROR_MESSAGE = {
  TASK_NOT_FOUND: 'Task Not Found',
  DOC_NOT_COMPLETELY_SIGNED: 'Document not signed by all member',
  USER_IDENTITY_VERIFICATION_PENDING: 'Please verify the identity first',
};
